[package]
name = "crosswords-rs"
version = "0.0.1"
authors = ["Andreas Fackler <AndreasFackler@gmx.de>"]

[features]
default = []
nightly = []

[dependencies]
getopts = "0.2.*"
rand = "0.3.*"
hyper = "0.6.*"
regex = "0.1.*"

