[package]
name = "crosswords-rs"
version = "0.0.1"
authors = ["Andreas Fackler <AndreasFackler@gmx.de>"]

[features]
default = []
nightly = []

[dependencies]
getopts = "~0.2.14"
itertools = "~0.5.9"
rand = "~0.3.15"
hyper = "~0.10.4"
regex = "~0.2.1"
