[package]
name = "crosswords-rs"
version = "0.0.1"
authors = ["Andreas Fackler <AndreasFackler@gmx.de>"]

[features]
default = []
nightly = []

[dependencies]
getopts = "~0.2.14"
itertools = "~0.6.0"
rand = "~0.3.15"
hyper = "~0.10.10"
regex = "~0.2.1"
